SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 720

SCREEN_TITLE = "Cellular Automata"

# Cell Generation
GRID_WIDTH = 75
GRID_HEIGHT = 200
GRID_BL_POS = (5, 5)

CELL_WIDTH = 10
CELL_HEIGHT = 10

START_DEATH_PERCENT = .5

# a cell can have up to 8 neighbors
MAX_NEIGHBORS_DEATH = 9
MIN_NEIGHBORS_DEATH = 4

MAX_NEIGHBORS_BIRTH = 9
MIN_NEIGHBORS_BIRTH = 8
